version: 0.9.5.{build}
branches:
  only:
  - master
build_script:
- bin\Prebuild.exe /target vs2010 /targetframework v4_5 /conditionals ISWIN;NET_4_5
- msbuild OpenMetaverse.sln /p:Configuration=Debug  /p:DefineConstants="ISWIN;NET_4_5"
artifacts:
- path: OpenMetaverse\bin
  name: WhiteCoreLibOMV
